<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>0.14.1</Version>
    <AssemblyName>rxt</AssemblyName>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>rxt</ToolCommandName>
    <PackageId>RapidXaml.Cli</PackageId>
    <Authors>Matt Lacey</Authors>
    <Company>Matt Lacey Ltd.</Company>
    <Description>Command-line interface for Rapid XAML Toolkit. Analyze and generate XAML from C#/VB.NET code.</Description>
    <PackageTags>XAML, MAUI, MVVM, UNO, UWP, WinUI, WPF, Xamarin.Forms, CLI</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://rapidxaml.dev</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mrlacey/rapid-xaml-toolkit</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.9.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.9.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="4.9.2" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RapidXaml.CustomAnalysis" Version="0.14.3" />
  </ItemGroup>

</Project>
